### ISSUE TITLE
waitForApproval strikes back

### ISSUE THREAD

**Issue by maaktweluit** [golemfactory/yagna-triage#47] opened 2021-01-28 13:44 UTC
mdt - MacOS+JS+0.3.0-alpha.3 - waitForApproval strikes back

    ```jsx
    2021-01-28 12:33:27 [yajsapi] info: Total Cost: 0.16396904263700002
    2021-01-28 12:33:28 [yajsapi] error: Release allocation: Error: Request failed with status code 500
    2021-01-28 12:33:28 [yajsapi] debug: GFTP server closed, code=null

    2021-01-28 12:34:15 [yajsapi] debug: waitForApproval(cfd1654fcb0c58f894ce1902771a734b90fa60f0e9b9892969451a278ce07c44) raised ApiException Error: Request failed with status code 408
    ```

**Comment by maaktweluit** [comment] 2021-01-28 14:08
Seems related to "printing logs after gftp closed"?

**Comment by tworec** [comment] 2021-02-05 22:30
duplicate of #40

**Closed as completed by tworec** 2021-02-05 22:30 UTC
Labels: sdk
