### ISSUE TITLE
Error while using golemsp in docker image setup

### ISSUE THREAD

**Issue by mat7ias** [golemfactory/yagna-triage#89] opened 2021-03-19 15:23 UTC
Users they have a a docker image setup running golemsp. It runs for a little while and then when they check status they see this in their logs and the node stops running:

```2021-03-19T13:19:16Z ERROR golemsp] `running: Command { std: "/usr/bin/yagna" "--json" "version" "show", kill_on_drop: false }` failed: [2021-03-19T13:19:16Z INFO  ya_service_bus::remote_router] trying to connect to: /tmp/yagna.sock
    [2021-03-19T13:19:16Z INFO  ya_service_bus::connection] started connection to gsb
    [2021-03-19T13:19:16Z ERROR ya_service_bus::connection] protocol error Invalid argument (os error 22)
    [2021-03-19T13:19:16Z INFO  ya_service_bus::connection] stopped connection to gsb
    Error: Called service `/local/version/check` is unavailable```

Related: https://github.com/golemfactory/yagna/issues/1107

**Comment by tworec** [comment] 2021-03-22 20:08
there is the same root cause as in golemfactory/yagna#1107 which is golemfactory/ya-service-bus#13
and will need golemfactory/ya-service-bus#16 to be solved. 

Closing as above issues are more than enough for single issue.

**Closed as completed by tworec** 2021-03-22 20:08 UTC
Labels: bug, provider, severity: minor, impact: low
