### ISSUE TITLE
minor yapapi - no detailed payment logs

### ISSUE THREAD

**Issue by ederenn** [golemfactory/yagna-triage#7] opened 2020-12-15 12:47 UTC
2rec - macOS+py+Python 3.8.6 - no detailed payments logs (attached blender-yapapi.log)

[blender-yapapi.log](https://github.com/golemfactory/yagna-triage/files/5695915/blender-yapapi.log)

```jsx
[2020-11-30 13:27:09,565 INFO yapapi.executor] Using log file `blender-yapapi.log`; in case of errors look for additional information there
yapapi version: 0.4.0a4
Using subnet: community.3
[2020-11-30 13:27:10,538 INFO yapapi.summary] Demand published on the market
[2020-11-30 13:27:12,591 INFO yapapi.summary] Received proposals from 1 providers so far
[2020-11-30 13:27:12,593 INFO yapapi.summary] Received proposals from 2 providers so far
[2020-11-30 13:27:12,593 INFO yapapi.summary] Received proposals from 3 providers so far
[2020-11-30 13:27:12,655 INFO yapapi.summary] Received proposals from 4 providers so far
[2020-11-30 13:27:12,702 INFO yapapi.summary] Received proposals from 5 providers so far
[2020-11-30 13:27:12,746 INFO yapapi.summary] Received proposals from 6 providers so far
[2020-11-30 13:27:12,816 INFO yapapi.summary] Received proposals from 7 providers so far
[2020-11-30 13:27:13,191 INFO yapapi.summary] Received proposals from 8 providers so far
[2020-11-30 13:27:13,418 INFO yapapi.summary] Received proposals from 9 providers so far
[2020-11-30 13:27:14,553 INFO yapapi.summary] Agreement proposed to provider 'whirlwind.3'
[2020-11-30 13:27:14,845 INFO yapapi.summary] Agreement confirmed by provider 'whirlwind.3'
[2020-11-30 13:27:15,850 INFO yapapi.summary] Task sent to provider 'whirlwind.3', task data: 0
[2020-11-30 13:27:16,863 INFO yapapi.summary] Agreement proposed to provider 'manchester.3'
[2020-11-30 13:27:20,692 INFO yapapi.summary] Agreement confirmed by provider 'manchester.3'
[2020-11-30 13:27:21,711 INFO yapapi.summary] Task sent to provider 'manchester.3', task data: 10
[2020-11-30 13:27:22,704 INFO yapapi.summary] Agreement proposed to provider 'ferranti.3'
[2020-11-30 13:27:24,705 INFO yapapi.summary] Agreement confirmed by provider 'ferranti.3'
[2020-11-30 13:27:25,687 INFO yapapi.summary] Task sent to provider 'ferranti.3', task data: 20
[2020-11-30 13:27:25,734 INFO yapapi.summary] Task computed by provider 'whirlwind.3', task data: 0
Task computed: Task(id=1, data=0), result: output_0.png, time: 0:00:09.983682
[2020-11-30 13:27:25,871 INFO yapapi.summary] Task sent to provider 'whirlwind.3', task data: 30
[2020-11-30 13:27:30,165 INFO yapapi.summary] Task computed by provider 'manchester.3', task data: 10
Task computed: Task(id=2, data=10), result: output_10.png, time: 0:00:08.554350
[2020-11-30 13:27:30,252 INFO yapapi.summary] Task sent to provider 'manchester.3', task data: 40
[2020-11-30 13:27:31,863 INFO yapapi.summary] Task computed by provider 'whirlwind.3', task data: 30
Task computed: Task(id=4, data=30), result: output_30.png, time: 0:00:06.128239
[2020-11-30 13:27:32,002 INFO yapapi.summary] Task sent to provider 'whirlwind.3', task data: 50
[2020-11-30 13:27:34,908 INFO yapapi.summary] Task computed by provider 'ferranti.3', task data: 20
Task computed: Task(id=3, data=20), result: output_20.png, time: 0:00:09.332370
[2020-11-30 13:27:35,529 INFO yapapi.summary] Task computed by provider 'manchester.3', task data: 40
Task computed: Task(id=5, data=40), result: output_40.png, time: 0:00:05.363998
[2020-11-30 13:27:38,048 INFO yapapi.summary] Task computed by provider 'whirlwind.3', task data: 50
Task computed: Task(id=6, data=50), result: output_50.png, time: 0:00:06.186399
[2020-11-30 13:27:38,051 INFO yapapi.summary] Computation finished in 27.7s
[2020-11-30 13:27:38,051 INFO yapapi.summary] Negotiated 3 agreements with 3 providers
[2020-11-30 13:27:38,051 INFO yapapi.summary] Provider 'whirlwind.3' computed 3 tasks
[2020-11-30 13:27:38,051 INFO yapapi.summary] Provider 'manchester.3' computed 2 tasks
[2020-11-30 13:27:38,052 INFO yapapi.summary] Provider 'ferranti.3' computed 1 tasks
[2020-11-30 13:27:41,798 INFO yapapi.summary] Total cost: 0.19140724633599998
[2020-11-30 13:27:41,897 INFO yapapi.summary] Executor shut down, total time: 31.5s
```

**Comment by shadeofblue** [comment] 2021-02-08 11:47
duplicate of https://github.com/golemfactory/yapapi/issues/236

**Closed as completed** 2021-02-10 00:25 UTC
Labels: enhancement, sdk
