### ISSUE TITLE
ProposalFailed: Broken pipe

### ISSUE THREAD

**Issue by mbenke** [golemfactory/yagna-triage#96] opened 2021-03-27 20:29 UTC
```
[2021-03-27 21:27:05,280 DEBUG yapapi.events] ProposalFailed(prop_id='R-3d4d4d655fb61ebd36d
04aad86e255843a76e8e555100f4085a4729d5e027c70', exc_info=(<class 'aiohttp.client_exceptions.ClientOSError'>, ClientOSError(32, 'Broken pipe'), <traceback object at 0x7f232ad3caf0>))
Traceback (most recent call last):                                                           File "/root/miniconda3/envs/rdkit/lib/python3.7/site-packages/yapapi/executor/__init__.py
", line 432, in find_offers                                                                    await proposal.respond(builder.properties, builder.constraints)                          File "/root/miniconda3/envs/rdkit/lib/python3.7/site-packages/yapapi/rest/market.py", lin
e 133, in respond                                                                              self._subscription.id, self.id, proposal 
  File "/root/miniconda3/envs/rdkit/lib/python3.7/site-packages/ya_market/api_client.py", line 201, in __call_api                     
    _request_timeout=_request_timeout,                                                       File "/root/miniconda3/envs/rdkit/lib/python3.7/site-packages/ya_market/rest.py", line 27
6, in POST                                                                                     body=body,                                                                               File "/root/miniconda3/envs/rdkit/lib/python3.7/site-packages/ya_market/rest.py", line 170, in request                                
    r = await self.pool_manager.request(**args)                                              File "/root/miniconda3/envs/rdkit/lib/python3.7/site-packages/aiohttp/client.py", line 54
4, in _request                                                                                 await resp.start(conn)
  File "/root/miniconda3/envs/rdkit/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 890, in start
    message, payload = await self._protocol.read()  # type: ignore                           File "/root/miniconda3/envs/rdkit/lib/python3.7/site-packages/aiohttp/streams.py", line 6
04, in read                                                                               
    await self._waiter                                                                    
aiohttp.client_exceptions.ClientOSError: [Errno 32] Broken pipe   
```

**Comment by mbenke** [comment] 2021-03-27 20:32
Also getting `Broken pipe` for other stuff:

```
[2021-03-27 21:26:04,429 DEBUG yapapi.events] WorkerFinished(agr_id='65138b1251596c3fe4b27755e059f9c7812548877f474780dd6aa3fdc8db74e5', exc_info=(<class 'aiohttp.client_exce
ptions.ClientOSError'>, ClientOSError(32, 'Broken pipe'), <traceback object at 0x7f25552cf870>))                                                                             
Traceback (most recent call last):                                                                                                                                           
  File "/root/miniconda3/envs/rdkit/lib/python3.7/site-packages/yapapi/executor/__init__.py", line 523, in start_worker                                                      
    await command_generator.athrow(*sys.exc_info())                                                                                                                          
  File "server.py", line 1219, in worker                                                                                                                                     
    yield ctx.commit(timeout=subtask_timeout)                                                                                                                                
  File "/root/miniconda3/envs/rdkit/lib/python3.7/site-packages/yapapi/executor/__init__.py", line 504, in start_worker                                                      
    cc.commands(), stream_output, deadline=batch_deadline                                                                                                                    
  File "/root/miniconda3/envs/rdkit/lib/python3.7/site-packages/yapapi/rest/activity.py", line 69, in send                                                                   
    batch_id = await self._api.call_exec(self._id, yaa.ExeScriptRequest(text=script_txt))                                                                                    
  File "/root/miniconda3/envs/rdkit/lib/python3.7/site-packages/ya_activity/api_client.py", line 201, in __call_api                                                          
    _request_timeout=_request_timeout,                                                                                                                                       
  File "/root/miniconda3/envs/rdkit/lib/python3.7/site-packages/ya_activity/rest.py", line 276, in POST                                                                      
    body=body,                                                                                                                                                               
  File "/root/miniconda3/envs/rdkit/lib/python3.7/site-packages/ya_activity/rest.py", line 170, in request                                                                   
    r = await self.pool_manager.request(**args)
  File "/root/miniconda3/envs/rdkit/lib/python3.7/site-packages/aiohttp/client.py", line 544, in _request
    await resp.start(conn)
  File "/root/miniconda3/envs/rdkit/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 890, in start
    message, payload = await self._protocol.read()  # type: ignore
  File "/root/miniconda3/envs/rdkit/lib/python3.7/site-packages/aiohttp/streams.py", line 604, in read
    await self._waiter
aiohttp.client_exceptions.ClientOSError: [Errno 32] Broken pipe
[2021-03-27 21:26:04,429 WARNING yapapi.summary] Activity failed on provider 'tintirimintiri', reason: [Errno 32] Broken pipe
[2021-03-27 21:26:04,429 DEBUG yapapi.events] ActivityCreateFailed(agr_id='7f7079a96a866716aaaf17925461618903f9e2fd144b205a2967d1b23653118d', exc_info=(<class 'aiohttp.clie$
t_exceptions.ClientOSError'>, ClientOSError(32, 'Broken pipe'), <traceback object at 0x7f25552cf050>))
Traceback (most recent call last):
  File "/root/miniconda3/envs/rdkit/lib/python3.7/site-packages/yapapi/executor/__init__.py", line 464, in start_worker
    act = await activity_api.new_activity(agreement.id)
  File "/root/miniconda3/envs/rdkit/lib/python3.7/site-packages/yapapi/rest/activity.py", line 43, in new_activity
    activity_id = await self._api.create_activity(agreement_id)
  File "/root/miniconda3/envs/rdkit/lib/python3.7/site-packages/ya_activity/api_client.py", line 201, in __call_api
    _request_timeout=_request_timeout,
  File "/root/miniconda3/envs/rdkit/lib/python3.7/site-packages/ya_activity/rest.py", line 276, in POST
    body=body,
  File "/root/miniconda3/envs/rdkit/lib/python3.7/site-packages/ya_activity/rest.py", line 170, in request
    r = await self.pool_manager.request(**args)
  File "/root/miniconda3/envs/rdkit/lib/python3.7/site-packages/aiohttp/client.py", line 544, in _request
    await resp.start(conn)
  File "/root/miniconda3/envs/rdkit/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 890, in start
    message, payload = await self._protocol.read()  # type: ignore
  File "/root/miniconda3/envs/rdkit/lib/python3.7/site-packages/aiohttp/streams.py", line 604, in read
    await self._waiter
aiohttp.client_exceptions.ClientOSError: [Errno 32] Broken pipe
```

**Comment by mbenke** [comment] 2021-03-29 19:18
[yagna-210329.log.gz](https://github.com/golemfactory/yagna-triage/files/6223970/yagna-210329.log.gz)

**Comment by mbenke** [comment] 2021-03-29 19:22
[yagna_r2021-03-27_00-00-03.log.gz](https://github.com/golemfactory/yagna-triage/files/6223998/yagna_r2021-03-27_00-00-03.log.gz)

**Comment by maaktweluit** [comment] 2021-03-31 11:41
Seems like 2 separate problems, could have the same root cause:

- collect_offeres() in yapapi
- Activity failed -> in yagna / activity

Actions:
1. @mbenke , could you check this after increasing the open file descriptors?
   - If YES, please notify tech-support about this and close this issue.
1. if the open files are checked, we will assign to sdk team to check their side
1. if both are not found core team will pick this up and investigate deeper.

**Comment by mbenke** [comment] 2021-03-31 12:41
@maaktweluit for analysis of file descriptors see https://github.com/golemfactory/yagna-triage/issues/99#issuecomment-811022572

**Comment by maaktweluit** [comment] 2021-04-07 10:59
@mbenke did you still see the broken pipe error after the file limit increase?

If so, please re-assign the issue to SDK team.

**Comment by mbenke** [comment] 2021-04-07 12:19
@maaktweluit yes, even today, e.g.

```
[2021-04-07 00:58:33,084 DEBUG yapapi.events] WorkerFinished(agr_id='f6396cd420b6bfc58817eeddfd41451344af8f7212adebb90681622731b60145', exc_info=(<class 'aiohttp.client_exceptions.ClientOSError'>, ClientOSError(32, 'Broken pipe'), <traceback object at 0x7fb30ea92d20>))                                                                            
aiohttp.client_exceptions.ClientOSError: [Errno 32] Broken pipe
[2021-04-07 00:58:33,084 WARNING yapapi.summary] Activity failed on provider 'TinCan', reason: [Errno 32] Broken pipe                                                       
aiohttp.client_exceptions.ClientOSError: [Errno 32] Broken pipe
[2021-04-07 12:21:25,462 DEBUG yapapi.events] WorkerFinished(agr_id='6e1e82707f58874e0cebb24fe4d470c500a9178c9bcb150f6f3c7d6423329543', exc_info=(<class 'aiohttp.client_exceptions.ClientOSError'>, ClientOSError(32, 'Broken pipe'), <traceback object at 0x7fb0e8a0c500>))                                                                            
aiohttp.client_exceptions.ClientOSError: [Errno 32] Broken pipe
[2021-04-07 12:21:25,462 WARNING yapapi.summary] Activity failed on provider 'eggqvq-s2', reason: [Errno 32] Broken pipe  
```

**Comment by mateuszsrebrny** [comment] 2021-04-08 08:26
Assigning to @shadeofblue @azawlocki to have a look from SDK point of view :)

**Comment by mateuszsrebrny** [comment] 2021-04-26 11:35
@mbenke is this issue still valid? SDK team seems to hope it kinds disappeared ;)
Please help us understand how important it is :)

**Comment by mbenke** [comment] 2021-04-26 11:52
@mateusz Seen today: 

```
yagna-1619379043-NF7eKe3PrLOZYeW9AZl32g.log:[2021-04-26 08:59:55,298 DEBUG yapapi.events] ProposalFailed(prop_id='R-333d77981c36cda5150eb1c3ab3280b5c15494a458b11e2ca752c6fd7aebe982', exc_info=(<class 'aiohttp.client_exceptions.ClientOSError'>, ClientOSError(32, 'Broken pipe'), <traceback object at 0x7f5ecb717640>))                             
yagna-1619379043-NF7eKe3PrLOZYeW9AZl32g.log:aiohttp.client_exceptions.ClientOSError: [Errno 32] Broken pipe 
```

so, alas, the issue seems still valid :(

**Comment by mbenke** [comment] 2021-04-28 10:07
```
[2021-04-28 11:55:15,281 ERROR yapapi.summary] Computation failed, reason: [Errno 32] Broken pipe  
```

**Comment by tworec** [comment] 2021-05-28 21:33
@filipgolem if it's done, pls close it.

**Closed as completed** 2021-06-02 06:31 UTC
Labels: bug, beta.2
