### ISSUE TITLE
ERROR ya_provider::tasks::task_manager] [ActivityCreated] Can't change state to Computing.

### ISSUE THREAD

**Issue by cryptobench** [golemfactory/yagna-triage#97] opened 2021-03-27 22:54 UTC
First time i've seen this error before. This was reported by **Thorax, Crash'n Burn model#5557** over on Discord.
![image](https://user-images.githubusercontent.com/33448819/112737026-9fbfb580-8f57-11eb-85e5-3fe21e0f4450.png)

**Logfile**
[ya-provider_rCURRENT.log](https://github.com/golemfactory/yagna-triage/files/6216561/ya-provider_rCURRENT.log)

**Comment by nieznanysprawiciel** [comment] 2021-03-31 11:17
It seems, Requestor was trying to create 2 activities at the same time. Provider rejects 2 activities and it is proper behavior, but we must investigate, why Requestor was trying to create the second Activity.
It is possible, that he didn't know about one of activities. Probably it is caused by one of problems that we already knew, but we will check it.

**Comment by maaktweluit** [comment] 2021-04-08 11:36
We will not check this in the current sprint, in 2 weeks (21-apr) we will re-evaluate priorities and schedule it

**Comment by jiivan** [comment] 2021-04-22 13:23
After talking to @nieznanysprawiciel and having a look by myself... I conclude it's a known issue of activity being timeout on requestor, but started successfully on provider side.  One solution is proposed in https://github.com/golemfactory/yagna/issues/1162

It's currently in our backlog.

**Comment by nieznanysprawiciel** [comment] 2023-01-17 16:18
Closing as duplicate of: https://github.com/golemfactory/yagna/issues/1162

**Closed as not planned by nieznanysprawiciel** 2023-01-17 16:18 UTC
Labels: bug, severity: major, impact: low
