### ISSUE TITLE
408/timeout after job is done

### ISSUE THREAD

**Issue by ederenn** [golemfactory/yagna-triage#40] opened 2021-01-19 13:57 UTC
- [ ] add annotation @ yastats.golem.netwrok

blue, 2rec - mac+js+ v `8af1e05`

```$ YAGNA_APPKEY=$(yagna app-key list --json | jq -r .values[0][1]) yarn js:blender -d --subnet-tag devnet-alpha.4
yarn run v1.22.10
$ node ./blender/blender.js -d --subnet-tag devnet-alpha.4
Using subnet: devnet-alpha.4
2021-01-19 12:12:10 [yajsapi] info: GFTP Version:0.1.2
2021-01-19 12:12:11 [yajsapi] info: Demand published on the market

--- cut---


2021-01-19 12:12:53 [yajsapi] info: Finished waiting for payments. Summary:
┌─────────┬─────────────────┬────────────────┬─────────────────────┐
│ (index) │  Provider Name  │ Tasks Computed │        Cost         │
├─────────┼─────────────────┼────────────────┼─────────────────────┤
│    0    │ '2rec-ubuntu.4' │       2        │ 0.05665342512400001 │
│    1    │    'reqc.4'     │       2        │   0.047586788083    │
│    2    │   'michal.4'    │       2        │ 0.04260764285599999 │
│    3    │    'etam.4'     │       0        │ '0 (no invoices?)'  │
└─────────┴─────────────────┴────────────────┴─────────────────────┘
2021-01-19 12:12:53 [yajsapi] info: Total Cost: 0.146847856063
2021-01-19 12:12:54 [yajsapi] debug: GFTP server closed, code=null
2021-01-19 12:13:51 [yajsapi] debug: waitForApproval(81922e327a8948fbe130ff2ee685c419c2806e83ba8ce9e3d32f6ba971102e7b) raised ApiException Error: Request failed with status code 408
✨  Done in 103.00s.
```

-------------------------

ederenn, Windows 10 pro, js

```jsx
2021-01-19 13:01:27 [yajsapi] info: Finished waiting for payments. Summary:
┌─────────┬─────────────────┬────────────────┬────────────────────┐
│ (index) │  Provider Name  │ Tasks Computed │        Cost        │
├─────────┼─────────────────┼────────────────┼────────────────────┤
│    0    │    'qbam.4'     │       2        │   0.049528828106   │
│    1    │   'michal.4'    │       2        │   0.046690830462   │
│    2    │ '2rec-ubuntu.4' │       1        │    0.0376243357    │
│    3    │   'mbenke.4'    │       0        │ '0 (no invoices?)' │
│    4    │   'mbenke.4'    │       0        │ '0 (no invoices?)' │
│    5    │    'reqc.4'     │       1        │   0.028568332339   │
└─────────┴─────────────────┴────────────────┴────────────────────┘
2021-01-19 13:01:28 [yajsapi] info: Total Cost: 0.162412326607
2021-01-19 13:01:28 [yajsapi] debug: GFTP server closed, code=null
2021-01-19 13:02:25 [yajsapi] debug: waitForApproval(12ed680249166fff9a3847f8ef91369fea0e33964b1987e1531aa3badf7eaf47) raised ApiException Error: Request failed with status code 408
Done in 107.22s.

```
Windows yagna logs:
[yagna_rCURRENT.log](https://github.com/golemfactory/yagna-triage/files/5836285/yagna_rCURRENT.log)

**Comment by tworec** [comment] 2021-01-19 15:00
I need more logs to investigate it

**Comment by tworec** [comment] 2021-01-19 17:24
I mean `yagna` and `yajsapi` logs @ DEBUG level + `market.db`

**Comment by filipgolem** [comment] 2021-01-20 10:40
In both `yajsapi` and `yapapi` we are calling `confirmAgreement(agreementId)` and then (after it returns) calling `waitForApproval(agreementId)` with a timeout parameter set to 90 seconds. `yagna` is replying with a `HTTP 408 Timeout` error. I tried to repeat this call for a few minutes, but it kept returning `408`.
```js
await this._api.confirmAgreement(this._id);
try {
  let { data: msg } = await this._api.waitForApproval(this._id, 90 (...));
(...)
```

**Comment by tworec** [comment] 2021-01-20 13:46
I was testing myself at `master` branch (`8af1e05`) and it is reproducible. In yagna logs I see that agreement confirmation (REST call) is finished **after** the agreement approval (by remote provider) is received, and this approval is rejected due to agreement state. We need to do it within transaction or swap order, first change Agreeement local state and then send it to the remote party (Provider) to approve. 


```
[2021-01-20T13:33:13Z INFO  ya_market::negotiation::requestor] Requestor '2rec' [0xcd340b8bd39eb3393e44019d6b0ebcfe8ac45359] created Agreement [R-0ff0c94b566e21a11483bab246ff38920b2a7c2d67caf5b6616e1ea892b72b85] from Proposal [R-05f50ff05421c359b756e553f2a5ae2c68de2242da1368124c520a0e41610b7e].
[2021-01-20T13:33:13Z INFO  actix_web::middleware::logger] 127.0.0.1:50531 "POST /market-api/v1/agreements HTTP/1.1" 200 66 "-" "axios/0.19.2" 0.000951
[2021-01-20T13:33:13Z INFO  actix_web::middleware::logger] 127.0.0.1:50531 "GET /market-api/v1/agreements/0ff0c94b566e21a11483bab246ff38920b2a7c2d67caf5b6616e1ea892b72b85 HTTP/1.1" 200 2920 "-" "axios/0.19.2" 0.000582
[2021-01-20T13:33:13Z INFO  actix_web::middleware::logger] 127.0.0.1:50532 "GET /payment-api/v1/invoiceEvents?timeout=5&afterTimestamp=2021-01-20T13%3A32%3A59.680680%2B00%3A00 HTTP/1.1" 200 2 "-" "axios/0.19.2" 0.000331
[2021-01-20T13:33:13Z INFO  actix_web::middleware::logger] 127.0.0.1:50522 "GET /activity-api/v1/activity/4edfe419184348e6a919c74896739927/exec/98d2e810d633481695ad04e271bd8d4d HTTP/1.1" 200 289146 "-" "axios/0.19.2" 0.649270
[2021-01-20T13:33:13Z DEBUG ya_market::protocol::negotiation::requestor] Negotiation API: Agreement [P-0ff0c94b566e21a11483bab246ff38920b2a7c2d67caf5b6616e1ea892b72b85] approved by [0x2e274d47d250ab44ccadf955bf0b102fe121da4d].
[2021-01-20T13:33:13Z INFO  actix_web::middleware::logger] 127.0.0.1:50519 "GET /activity-api/v1/activity/0ec0b6b4574b4007bbfef9ba78f4433f/exec/2e072832c0944f8f8d320a0337c3671c HTTP/1.1" 200 865 "-" "axios/0.19.2" 0.347980
[2021-01-20T13:33:13Z INFO  actix_web::middleware::logger] 127.0.0.1:50526 "GET /activity-api/v1/activity/481375cd1dca455e87b4bd2314997284/exec/8d0f1168c2984209ae112b56f2b6c512 HTTP/1.1" 200 589 "-" "axios/0.19.2" 1.302740
[2021-01-20T13:33:13Z INFO  actix_web::middleware::logger] 127.0.0.1:50529 "GET /activity-api/v1/activity/fcac4943dbce4e9d9cdd11be5a79997a/exec/f70b5a72ad9444ddb5f77786ae8e1856 HTTP/1.1" 200 451 "-" "axios/0.19.2" 0.348697
[2021-01-20T13:33:13Z DEBUG ya_service_bus::typed] Call to AgreementApproved failed: Remote failed to approve. Error: Agreement [R-0ff0c94b566e21a11483bab246ff38920b2a7c2d67caf5b6616e1ea892b72b85] in state Proposal, can't be approved.
[2021-01-20T13:33:13Z INFO  ya_market::negotiation::requestor] Requestor '2rec' [0xcd340b8bd39eb3393e44019d6b0ebcfe8ac45359] confirmed Agreement [R-0ff0c94b566e21a11483bab246ff38920b2a7c2d67caf5b6616e1ea892b72b85] and sent to Provider.
[2021-01-20T13:33:13Z INFO  actix_web::middleware::logger] 127.0.0.1:50531 "POST /market-api/v1/agreements/0ff0c94b566e21a11483bab246ff38920b2a7c2d67caf5b6616e1ea892b72b85/confirm HTTP/1.1" 204 0 "-" "axios/0.19.2" 0.318655
```

**Comment by tworec** [comment] 2021-01-29 19:47
closing via golemfactory/yagna#953

**Comment by maaktweluit** [comment] 2021-02-03 13:08
Today during the testing session i had this error again after the task was completed:
```
2021-02-03 13:01:32 [yajsapi] debug: waitForApproval(9639c757ea4775c02a0aa36c1046ccaa51d60d63c800a8d4c8c4b3d31796ae46) raised ApiException Error: Request failed with status code 408
```

**Comment by tworec** [comment] 2021-02-09 08:57
closing via golemfactory/yagna#1014

**Closed as completed by tworec** 2021-02-09 08:57 UTC
