### ISSUE TITLE
No offers have been collected from the market 

### ISSUE THREAD

**Issue by ederenn** [golemfactory/yagna-triage#39] opened 2021-01-19 13:48 UTC
Reporter: mdt
 MacOS + js

```
Muhammeds-MacBook-Pro-4:examples mdt$ yarn js:blender --subnet-tag devnet-alpha.4
yarn run v1.22.10
$ node ./blender/blender.js --subnet-tag devnet-alpha.4
Using subnet: devnet-alpha.4
2021-01-19 12:33:38 [yajsapi] info: GFTP Version:0.1.2
2021-01-19 12:33:39 [yajsapi] info: Demand published on the market
2021-01-19 12:33:59 [yajsapi] warn: No offers have been collected from the market for
            20s. Make sure you're using the latest released versions of yagna and yajsapi, and the correct subnet.
2021-01-19 12:34:20 [yajsapi] warn: No offers have been collected from the market for
            40s. Make sure you're using the latest released versions of yagna and yajsapi, and the correct subnet.
2021-01-19 12:34:40 [yajsapi] warn: No offers have been collected from the market for
            60s. Make sure you're using the latest released versions of yagna and yajsapi, and the correct subnet.
2021-01-19 12:35:00 [yajsapi] warn: No offers have been collected from the market for
            80s. Make sure you're using the latest released versions of yagna and yajsapi, and the correct subnet.
2021-01-19 12:35:20 [yajsapi] warn: No offers have been collected from the market for
            100s. Make sure you're using the latest released versions of yagna and yajsapi, and the correct subnet.
2021-01-19 12:35:40 [yajsapi] warn: No offers have been collected from the market for
            120s. Make sure you're using the latest released versions of yagna and yajsapi, and the correct subnet.
2021-01-19 12:36:00 [yajsapi] warn: No offers have been collected from the market for
            140s. Make sure you're using the latest released versions of yagna and yajsapi, and the correct subnet.
2021-01-19 12:36:20 [yajsapi] warn: No offers have been collected from the market for
            160s. Make sure you're using the latest released versions of yagna and yajsapi, and the correct subnet.
```

[yagna_rCURRENT.log](https://github.com/golemfactory/yagna-triage/files/5836236/yagna_rCURRENT.log)

[market.zip](https://github.com/golemfactory/yagna-triage/files/5836243/market.zip)

---------------------------

Happend also on Windows 10
Reporter: ederenn

 ` No offers have been collected from the market`
problem solved by restarting yagna and js

**Comment by tworec** [comment] 2021-01-19 18:41
At the period you were trying to get Proposal (ie. between `2021-01-19 12:33:38` and `2021-01-19 12:36:20`) there were no Offers for `devnet-alpha.4` at your host. Contents of `market.db` witnesses that they have appeared @ `2021-01-19 11:45:13.219` ( see `insertion_ts` column below), probably after `yagna` daemon restart, because attached  `yagna_rCURRENT.log` have no history for that moment.

I'd need to have `yagna_rCURRENT.log` @ `DEBUG` level from such a case, to investigate it further.
It could be due to your network lag, or due to lag of central GSB router (serving as net hub) or due to local GSB disconnect which is [known issue unfortunately](https://github.com/golemfactory/yagna/issues/752), or some other unknown yet issue.   


```sql
sqlite> select count(1) from market_offer where insertion_ts < '2021-01-19 11:36:20' and expiration_ts > '2021-01-19 11:36:20' and properties like '%devnet-alpha.4%' limit 1;
0
sqlite> select count(1) from market_offer where expiration_ts > '2021-01-19 11:36:20' and properties like '%devnet-alpha.4%' limit 1; 
15
sqlite> select creation_ts,insertion_ts from market_offer where expiration_ts > '2021-01-19 11:36:20' and properties like '%devnet-alpha.4%';
```
|creation_ts|insertion_ts|
|---|---|
|2021-01-19 11:36:17.417718646|2021-01-19 11:45:13.219|
|2021-01-19 11:36:17.477924092|2021-01-19 11:45:13.219|
|2021-01-19 11:36:55.481485049|2021-01-19 11:45:13.221|
|2021-01-19 11:36:55.539577874|2021-01-19 11:45:13.221|
|2021-01-19 11:45:38.353571884|2021-01-19 11:45:39.020|
|2021-01-19 11:45:38.423640656|2021-01-19 11:45:39.146|
|2021-01-19 11:45:49.834218205|2021-01-19 11:45:50.041|
|2021-01-19 11:45:49.869042754|2021-01-19 11:45:50.180|
|2021-01-19 11:45:49.870239381|2021-01-19 11:45:50.417|
|2021-01-19 11:45:49.879380963|2021-01-19 11:45:50.587|
|2021-01-19 11:45:49.911111557|2021-01-19 11:45:50.741|
|2021-01-19 11:45:49.911600404|2021-01-19 11:45:50.898|
|2021-01-19 11:45:50.639543318|2021-01-19 11:45:51.074|
|2021-01-19 11:45:50.708317688|2021-01-19 11:45:51.223|
|2021-01-19 12:00:49.784739728|2021-01-19 12:00:50.006|

**Comment by mateuszsrebrny** [comment] 2021-02-11 13:16
It seems reproducing it after such time will be hard. closing this now

**Closed as completed by mateuszsrebrny** 2021-02-11 13:16 UTC
