### ISSUE TITLE
vm image corrupted on a provider

### ISSUE THREAD

**Issue by ederenn** [golemfactory/yagna-triage#161] opened 2021-11-23 12:07 UTC
Name: blue (actually, mbenke.t)
yagna version: ?
OS+lang+version (if applicable): ?

```
[2021-11-23T12:40:55.283+0100 WARNING yapapi.summary] [Job 1] Activity failed on provider 'mbenke.t'; reason: Command '{'deploy': {}}' failed on provider; message: 'Local service error: Transfer error: Downloaded VM image is corrupted: calculated hash 9f169103f87287c77edcfd84a5dd4ca588f61449ef66502b1d4f7642 differs from the expected one 055911c811e56da4d75ffc928361a78ed13077933ffa8320fb1ec2db'
```

**Comment by shadeofblue** [comment] 2021-11-24 14:41
duplicate of #150

**Closed as completed by shadeofblue** 2021-11-24 14:41 UTC
