### ISSUE TITLE
failed to create activity

### ISSUE THREAD

**Issue by maaktweluit** [golemfactory/yagna-triage#34] opened 2021-01-14 12:19 UTC
GJ - mac python 3.6 - failed to create activity
`[2021-01-14 12:48:58,210 ERROR yapapi.rest] Failed to create activity for agreement 5985baa57bcfbddf81956c4e90eff336b0c0422a388fd1bf136b6c4872af7ae8`

    [blender-yapapi.log](https://s3-us-west-2.amazonaws.com/secure.notion-static.com/c5795cd3-f69d-45fc-ae93-19ed085b5e98/blender-yapapi.log)

**Comment by ederenn** [comment] 2021-01-14 14:34
duplicate of https://github.com/golemfactory/yagna/issues/921

**Closed as completed by ederenn** 2021-01-14 14:34 UTC
