### ISSUE TITLE
Offer expired

### ISSUE THREAD

**Issue by maaktweluit** [golemfactory/yagna-triage#81] opened 2021-02-25 14:30 UTC
Etam - Linux - Offer expired

```
    [2021-02-25T11:13:00Z WARN  ya_market::matcher::handlers] Failed to save Offer [61c55e96e8fc4886a40a6225bb1da845-ada1e66ae23db2e574842d425fdc8791ea2b9044a00b2a6376c2f2824f881eb6]. Error: Offer [61c55e96e8fc4886a40a6225bb1da845-ada1e66ae23db2e574842d425fdc8791ea2b9044a00b2a6376c2f2824f881eb6] expired.
    [2021-02-25T11:13:00Z WARN  ya_market::matcher::handlers] Failed to save Offer [67c957a142bb45ad8c0a8d00c755f9d3-78541822906bab5503fd66fbc262bc38a6362588d12854cb5d617a3e76191914]. Error: Offer [67c957a142bb45ad8c0a8d00c755f9d3-78541822906bab5503fd66fbc262bc38a6362588d12854cb5d617a3e76191914] expired.
    [2021-02-25T11:13:00Z WARN  ya_market::matcher::handlers] Failed to save Offer [7f6e5323862d45edae513315b10e2567-22740c55ad4c98a791e1cdb6e9e484bdf8c0621e966d43c66ba50c62fede484e]. Error: Offer [7f6e5323862d45edae513315b10e2567-22740c55ad4c98a791e1cdb6e9e484bdf8c0621e966d43c66ba50c62fede484e] expired.
```

**Comment by mateuszsrebrny** [comment] 2021-02-25 14:55
Duplicate of https://github.com/golemfactory/yagna/issues/1087

**Closed as completed by mateuszsrebrny** 2021-02-25 14:55 UTC
Labels: duplicate, beta.1
