### ISSUE TITLE
Executor shut down before the computation finished

### ISSUE THREAD

**Issue by ederenn** [golemfactory/yagna-triage#14] opened 2020-12-16 15:47 UTC
Asignee: Artur Zawłocki
Reporter: BlueShade, Phillip Jensen

NOTE (GJ): We suspect this has something to do with exe-unit failing, please investigate and re-assign if required

  blue - osx mojave+python/blender+Python 3.8.5 - Executor shut down before the computation finished (attach `yapapi-blender.log`)

    
[blender-yapapi (1).log](https://github.com/golemfactory/yagna-triage/files/5703794/blender-yapapi.1.log)

    ```jsx
    $ python3 blender.py
    Adding /Users/blue/yapapi/examples to sys.path.
    [2020-11-26 13:06:49,498 INFO yapapi.executor] Using log file `blender-yapapi.log`; in case of errors look for additional information there
    yapapi version: 0.4.0a4
    Using subnet: community.3
    [2020-11-26 13:06:52,295 INFO yapapi.summary] Demand published on the market
    [2020-11-26 13:07:12,267 WARNING yapapi.summary] 23 offers have been collected from the market, but no provider has responded for 20s. Make sure you're using the latest released versions of yagna and yapapi, and the correct subnet.
    [2020-11-26 13:07:18,903 INFO yapapi.summary] Received proposals from 1 providers so far
    [2020-11-26 13:07:19,762 INFO yapapi.summary] Received proposals from 2 providers so far
    [2020-11-26 13:07:19,848 INFO yapapi.summary] Received proposals from 3 providers so far
    [2020-11-26 13:07:20,370 INFO yapapi.summary] Agreement proposed to provider 'jamuszyn'
    [2020-11-26 13:07:23,868 INFO yapapi.summary] Agreement confirmed by provider 'jamuszyn'
    [2020-11-26 13:07:24,945 INFO yapapi.summary] Task sent to provider 'jamuszyn', task data: 0
    [2020-11-26 13:07:25,892 INFO yapapi.summary] Agreement proposed to provider 'friendly-error'
    [2020-11-26 13:07:36,861 INFO yapapi.summary] Task computed by provider 'jamuszyn', task data: 0
    Task computed: Task(id=1, data=0), result: output_0.png, time: 0:00:12.081401
    [2020-11-26 13:07:37,269 INFO yapapi.summary] Task sent to provider 'jamuszyn', task data: 10
    [2020-11-26 13:07:44,055 INFO yapapi.summary] Task computed by provider 'jamuszyn', task data: 10
    Task computed: Task(id=2, data=10), result: output_10.png, time: 0:00:07.173038
    [2020-11-26 13:07:44,389 INFO yapapi.summary] Task sent to provider 'jamuszyn', task data: 20
    [2020-11-26 13:07:54,888 INFO yapapi.summary] Task computed by provider 'jamuszyn', task data: 20
    [2020-11-26 13:07:54,934 INFO yapapi.summary] Received proposals from 3 providers so far
    Task computed: Task(id=3, data=20), result: output_20.png, time: 0:00:10.793051
    [2020-11-26 13:07:55,203 INFO yapapi.executor] Waiting for 1 workers to finish...
    [2020-11-26 13:07:55,432 ERROR yapapi.summary] Computation failed, reason: [Errno 54] Connection reset by peer
    [2020-11-26 13:07:58,549 INFO yapapi.executor] Waiting for all services to finish...
    [2020-11-26 13:07:59,612 INFO yapapi.summary] Executor shut down, total time: 67.8s
    ```

    - [ ]  Phillip - OSx Catalina 10.15.7+lib+ Python 3.8.0 (if applicable) - No results, just hanging (attach `yapapi-blender.log`)

      
[blender-yapapi (2).log](https://github.com/golemfactory/yagna-triage/files/5703797/blender-yapapi.2.log)

**Comment by azawlocki** [comment] 2021-07-13 14:47
Probably a duplicate of https://github.com/golemfactory/yagna-triage/issues/138 (I'm not sure since the attached log file is from another run).

**Closed as completed** 2021-07-13 14:48 UTC
Labels: bug
