### ISSUE TITLE
Subscription expired to soon (leading to failed computation)

### ISSUE THREAD

**Issue by mbenke** [golemfactory/yagna-triage#95] opened 2021-03-27 10:15 UTC
Created a yapapi worker with expiation set to 153 minutes:

```
[2021-03-27 08:08:21,814 DEBUG yapapi.executor] Creating Executor instance; parameters: {'self': <yapapi.executor.Executor object at 0x7f7eb6a41c50>, 'package': _VmPackage(\
repo_url='http://yacn2.dev.golem.network:8000', image_hash='4a940507007a403d5acf4938eb00432b4b7894500d2d84dbcc7155a7', constraints=_VmConstrains(min_mem_gib=1.5, min_storag\
e_gib=2.0, cores=1)), 'max_workers': 80, 'timeout': datetime.timedelta(seconds=9180), 'budget': 20.0, 'strategy': run_on_golem.<locals>.LocalMarketStrategy(), 'subnet_tag':\
 'public-beta', 'driver': None, 'network': 'mainnet', 'event_consumer': <bound method SummaryLogger.log of <yapapi.log.SummaryLogger object at 0x7f7eb6a41fd0>>}
[2021-03-27 08:08:21,848 DEBUG yapapi.executor] Creating allocation using payment platform `zksync-mainnet-glm`
[2021-03-27 08:08:22,117 DEBUG yapapi.events] ComputationStarted(expires=datetime.datetime(2021, 3, 27, 9, 41, 21, 814859, tzinfo=datetime.timezone.utc))
```

But it has been terminated prematurely, apparently due to subscription having expired earlier than that:

```
[2021-03-27 10:35:44,032 DEBUG yapapi.events] ComputationFinished(exc_info=(<class 'ya_market.exceptions.ApiException'>, ApiException(), <traceback object at 0x7f7b4f181870\
>))
Traceback (most recent call last):
  File "/root/miniconda3/envs/rdkit/lib/python3.7/site-packages/yapapi/executor/__init__.py", line 384, in find_offers
    async for proposal in proposals:
  File "/root/miniconda3/envs/rdkit/lib/python3.7/site-packages/yapapi/rest/market.py", line 202, in events
    proposals = await self._api.collect_offers(self._id, timeout=10, max_events=10)
  File "/root/miniconda3/envs/rdkit/lib/python3.7/site-packages/ya_market/api_client.py", line 205, in __call_api
    raise e
  File "/root/miniconda3/envs/rdkit/lib/python3.7/site-packages/ya_market/api_client.py", line 201, in __call_api
    _request_timeout=_request_timeout,
  File "/root/miniconda3/envs/rdkit/lib/python3.7/site-packages/ya_market/rest.py", line 198, in GET
    query_params=query_params,
  File "/root/miniconda3/envs/rdkit/lib/python3.7/site-packages/ya_market/rest.py", line 180, in request
    raise ApiException(http_resp=r)
ya_market.exceptions.ApiException: (404)
Reason: Not Found
HTTP response headers: <CIMultiDictProxy('Content-Length': '135', 'Content-Type': 'application/json', 'Date': 'Sat, 27 Mar 2021 09:35:02 GMT')>
HTTP response body: {"message":"Subscription [5c9bc186fab24cf7994e868a8a938a84-6714b1961651294cebab6969ea45059fde2a535bc5af5ed25a4403f523d8185a] expired."}

```

**Comment by mbenke** [comment] 2021-03-29 19:18
[yagna-210329.log.gz](https://github.com/golemfactory/yagna-triage/files/6223970/yagna-210329.log.gz)

**Comment by mbenke** [comment] 2021-03-29 19:22
[yagna_r2021-03-27_00-00-03.log.gz](https://github.com/golemfactory/yagna-triage/files/6223998/yagna_r2021-03-27_00-00-03.log.gz)

**Comment by nieznanysprawiciel** [comment] 2021-03-31 11:44
Subscription expiration is not related to computations. Probably something different happened. But still we need to check what it was.

**Comment by tworec** [comment] 2021-03-31 13:11
@mbenke can you elaborate on why you perceive the `high impact` and `major severity`?

**Comment by mbenke** [comment] 2021-03-31 14:10
@tworec see https://github.com/golemfactory/yagna-triage/issues/98#issuecomment-811098213

**Comment by maaktweluit** [comment] 2021-04-08 11:51
@nieznanysprawiciel will look at this next week and get back to you.

**Comment by nieznanysprawiciel** [comment] 2021-04-12 12:19
I see that many Agreements were terminated dues to 2 reasons:
- Requestor isn't accepting DebitNotes in time (2m)
- No activity created within 90s (this one is more interesting in context of this error, what I will explain in a moment)

Message about expired subscription appears, because after Agreements are terminated, Executor needs new Providers. Than he tries to sign new Agreements and the process fails, because subscription is already expired.
It is interesting, because it seems, that he had idle Agreements, because message "No activity created within 90s" appears.

Things that need to be addressed (@azawlocki ):
- yapapi must be able to create new Agreements even after subscription expires (new subscription? or what?)
- why no activities are created for some of Agreements if there is work to do
- problem with not accepting DebitNotes still exists :(

@mbenke I couldn't track this specific Subscription, that your logs pointed to, because `yapapi` logs, that you attached, are from different timespan.

**Comment by mbenke** [comment] 2021-04-12 15:01
@nieznanysprawaiciel Oops, I indeed seem to have attached wrong yapapi log. This one should be better:

[yapapi210327.log.gz](https://github.com/golemfactory/yagna-triage/files/6297700/yapapi210327.log.gz)

**Comment by filipgolem** [comment] 2021-04-13 10:18
There are three separate issues here:

1. `Requestor isn't accepting DebitNotes in time (2m).` That was supposed to be fixed by decreasing the frequency of debit notes from providers. Am I right that this did not completely fix the problem? @nieznanysprawiciel
2. Subscription expires after e.g. 5 minutes. This will be solved by adding a new parameter to `yagna` REST API `subscribe_demand` endpoint.
3. Agreements with no activities are not used when new activities are needed. @azawlocki, can you share your thoughts about it? Is it related to the agreement pool? I don't think it's critical.

**Comment by nieznanysprawiciel** [comment] 2021-04-13 10:57
1. Not all Providers in the network updated themself probably...

**Comment by tworec** [comment] 2021-04-13 11:33
> 1. Not all Providers in the network updated themself probably...

@nieznanysprawiciel what you are referring to?

**Comment by azawlocki** [comment] 2021-04-15 10:16
@mbenke As for the original issue, I can confirm the computation exiting due to subscription expiration is a bug in `yapapi`, the requestor should not be able to create new agreements, but the existing activities should continue. An issue for this bug: https://github.com/golemfactory/yapapi/issues/340.

**Comment by azawlocki** [comment] 2021-04-15 15:18
OTOH, as I mentioned in https://github.com/golemfactory/yapapi/issues/340, subscription expiration date is the same as the computation deadline used by Executor, so the computation would fail anyway, due to Executor timeout.

**Comment by azawlocki** [comment] 2021-04-15 15:30
@nieznanysprawiciel Agreements and debit notes aside, the original issue seems to be why the subscription that was set to expire after 153 minutes expired after approximately 60 minutes.

Relevant snippets from yapapi210327.log.gz:
```
[2021-03-27 08:08:21,814 DEBUG yapapi.executor] Creating Executor instance; parameters: {'self': <yapapi.executor.Executor object at 0x7f7eb6a41c50>, 'package': _VmPackage(repo_url='http://yacn2.dev.golem.network:8000', image_hash='4a940507007a403d5acf4938eb00432b4b7894500d2d84dbcc7155a7', constraints=_VmConstrains(min_mem_gib=1.5, min_storage_gib=2.0, cores=1)), 'max_workers': 80, 'timeout': datetime.timedelta(seconds=9180), 'budget': 20.0, 'strategy': run_on_golem.<locals>.LocalMarketStrategy(), 'subnet_tag': 'public-beta', 'driver': None, 'network': 'mainnet', 'event_consumer': <bound method SummaryLogger.log of <yapapi.log.SummaryLogger object at 0x7f7eb6a41fd0>>}                                                                                                                                                                     
```
Note the timeout set to 9180 seconds, it is used to set `golem.srv.comp.expiration` property of the subscription.
```
[2021-03-27 08:08:22,676 DEBUG yapapi.events] SubscriptionCreated(sub_id='343dedb4b13e4a78911d7e1dbd5ef167-17d1d6dbfa48b8744eabfc387ae3b25aca7352d21eb5ef7300b21be2f51007f0')                                      
```
Then, after 60 minutes Market API calls start to return errors with the message "Subscription not found":
```
[2021-03-27 09:09:13,151 DEBUG yapapi.events] ProposalFailed(prop_id='R-e5e4d37662aacf48c9bc48d1de2cd7520be11e31d0f3d8a158cffd40c7481131', exc_info=(<class 'ya_market.exceptions.ApiException'>, ApiException(), \
<                                                                                                                                                                                                                  
traceback object at 0x7f7d8f0cd8c0>))                                                                                                                                                                              
Traceback (most recent call last):                                                                                                                                                                                 
  File "/root/miniconda3/envs/rdkit/lib/python3.7/site-packages/yapapi/executor/__init__.py", line 432, in find_offers                                                                                             
    await proposal.respond(builder.properties, builder.constraints)                                                                                                                                                
  File "/root/miniconda3/envs/rdkit/lib/python3.7/site-packages/yapapi/rest/market.py", line 133, in respond                                                                                                       
    self._subscription.id, self.id, proposal                                                                                                                                                                       
  File "/root/miniconda3/envs/rdkit/lib/python3.7/site-packages/ya_market/api_client.py", line 205, in __call_api                                                                                                  
    raise e                                                                                                                                                                                                        
  File "/root/miniconda3/envs/rdkit/lib/python3.7/site-packages/ya_market/api_client.py", line 201, in __call_api                                                                                                  
    _request_timeout=_request_timeout,                                                                                                                                                                             
  File "/root/miniconda3/envs/rdkit/lib/python3.7/site-packages/ya_market/rest.py", line 276, in POST                                                                                                              
    body=body,                                                                                                                                                                                                     
  File "/root/miniconda3/envs/rdkit/lib/python3.7/site-packages/ya_market/rest.py", line 180, in request                                                                                                           
    raise ApiException(http_resp=r)                                                                                                                                                                                
ya_market.exceptions.ApiException: (400)                                                                                                                                                                           
Reason: Bad Request                                                                                                                                                                                                
HTTP response headers: <CIMultiDictProxy('Content-Length': '140', 'Content-Type': 'application/json', 'Date': 'Sat, 27 Mar 2021 08:08:57 GMT')>                                                                    
HTTP response body: {"message":"Subscription [343dedb4b13e4a78911d7e1dbd5ef167-17d1d6dbfa48b8744eabfc387ae3b25aca7352d21eb5ef7300b21be2f51007f0] wasn't found."}       
```
and finally Market API reports that the subscription expired:
```
[2021-03-27 09:11:52,732 DEBUG yapapi.events] ComputationFinished(exc_info=(<class 'ya_market.exceptions.ApiException'>, ApiException(), <traceback object at 0x7f79c5243e60>))                                    
Traceback (most recent call last):                                                                                                                                                                                 
  File "/root/miniconda3/envs/rdkit/lib/python3.7/site-packages/yapapi/executor/__init__.py", line 384, in find_offers                                                                                             
    async for proposal in proposals:                                                                                                                                                                               
  File "/root/miniconda3/envs/rdkit/lib/python3.7/site-packages/yapapi/rest/market.py", line 202, in events                                                                                                        
    proposals = await self._api.collect_offers(self._id, timeout=10, max_events=10)                                                                                                                                
  File "/root/miniconda3/envs/rdkit/lib/python3.7/site-packages/ya_market/api_client.py", line 205, in __call_api                                                                                                  
    raise e                                                                                                                                                                                                        
  File "/root/miniconda3/envs/rdkit/lib/python3.7/site-packages/ya_market/api_client.py", line 201, in __call_api                                                                                                  
    _request_timeout=_request_timeout,                                                                                                                                                                             
  File "/root/miniconda3/envs/rdkit/lib/python3.7/site-packages/ya_market/rest.py", line 198, in GET                                                                                                               
    query_params=query_params,                                                                                                                                                                                     
  File "/root/miniconda3/envs/rdkit/lib/python3.7/site-packages/ya_market/rest.py", line 180, in request                                                                                                           
    raise ApiException(http_resp=r)                                                                                                                                                                                
ya_market.exceptions.ApiException: (404)                                                                                                                                                                           
Reason: Not Found                                                                                                                                                                                                  
HTTP response headers: <CIMultiDictProxy('Content-Length': '135', 'Content-Type': 'application/json', 'Date': 'Sat, 27 Mar 2021 08:11:52 GMT')>                                                                    
HTTP response body: {"message":"Subscription [343dedb4b13e4a78911d7e1dbd5ef167-17d1d6dbfa48b8744eabfc387ae3b25aca7352d21eb5ef7300b21be2f51007f0] expired."}                             
```

**Comment by azawlocki** [comment] 2021-04-16 08:04
Relevant logs from the daemon:
```
[2021-03-27T07:08:22Z INFO  ya_market::matcher] Subscribed new Demand: [343dedb4b13e4a78911d7e1dbd5ef167-17d1d6dbfa48b8744eabfc387ae3b25aca7352d21eb5ef7300b21be2f51007f0] using identity: requestor [0xa96d3f3e177687fb0b5f990d5c4000923b49430b]
...
[2021-03-27T07:08:22Z INFO  ya_market::negotiation::common] New Proposal [R-3175fd1ec6ec2dcb6ff2cb1a3cc09c7940b801cb0ab96775329bad2adeb09835] (Offer [a7a7206ca5e34d45bb0e1e1436ed3e7c-502ac968bc29e3e0eb2e8929bc5605133c7065acb887ae71bca4090aa1b3ab09], Demand [343dedb4b13e4a78911d7e1dbd5ef167-17d1d6dbfa48b8744eabfc387ae3b25aca7352d21eb5ef7300b21be2f51007f0])
...
[2021-03-27T08:06:28Z INFO  ya_market::negotiation::common] New Proposal [R-41b798e89d8bd8b8743888a5983fa4730466c1fb568677e81d58b126762cf439] (Offer [d4198ac6e110495e9b767ce88a5c25a1-787fc8918720ac02cb212fe8309eec8633cd545c6917a8adc1b2b408bb6f3e67], Demand [343dedb4b13e4a78911d7e1dbd5ef167-17d1d6dbfa48b8744eabfc387ae3b25aca7352d21eb5ef7300b21be2f51007f0])
```
After 60 minutes:
```
[2021-03-27T08:08:24Z WARN  ya_market::negotiation::common] Failed to regenerate Proposal after Agreement [R-fafddbfd6a5eece88e8407fed3215866bb5ef3f95986136e57d056299b24839e] termination. Failed regenerate proposal: Demand [343dedb4b13e4a78911d7e1dbd5ef167-17d1d6dbfa48b8744eabfc387ae3b25aca7352d21eb5ef7300b21be2f51007f0] not found..
```

**Comment by azawlocki** [comment] 2021-04-16 13:18
@mbenke @nieznanysprawiciel As for the debit notes, it seems that some providers were sending debit notes every 6 seconds:
```
[2021-03-27 08:09:21,463 DEBUG yapapi.events] DebitNoteReceived(agr_id='76203aeadaef205243a2f21712529b4ef3c7cb7977682f2200c10e1eaca96f59', note_id='4c7b2fde-b72b-44b4-b3a7-c57510621da8', amount='0.000548608862983333')
[2021-03-27 08:09:21,558 DEBUG yapapi.events] DebitNoteReceived(agr_id='eb17afc1b55b8ee04c530233008c2cc72c40e4b64aa8938fef9003564db33a0b', note_id='b653e947-4922-4445-89c4-fc37d640baa7', amount='0.000083872918433333')
[2021-03-27 08:09:26,469 DEBUG yapapi.events] DebitNoteReceived(agr_id='76203aeadaef205243a2f21712529b4ef3c7cb7977682f2200c10e1eaca96f59', note_id='69ba0306-17ec-4e94-88ee-0228eac33932', amount='0.001526387536161111')
[2021-03-27 08:09:31,820 DEBUG yapapi.events] DebitNoteReceived(agr_id='eb17afc1b55b8ee04c530233008c2cc72c40e4b64aa8938fef9003564db33a0b', note_id='ab1aa90e-482c-4a9f-9d7d-6869bf4229f9', amount='0.000631092969788889')
[2021-03-27 08:09:31,932 DEBUG yapapi.events] DebitNoteReceived(agr_id='76203aeadaef205243a2f21712529b4ef3c7cb7977682f2200c10e1eaca96f59', note_id='69f3fa19-a129-4ad7-9896-2478f86027fe', amount='0.01136527650533889')
[2021-03-27 08:09:37,646 DEBUG yapapi.events] DebitNoteReceived(agr_id='eb17afc1b55b8ee04c530233008c2cc72c40e4b64aa8938fef9003564db33a0b', note_id='cf284df6-2429-46ce-aecc-dba4dcbe6b1b', amount='0.001310261700544445')
```
After analysing yapapi210327.log.gz I estimated that for around 40% of agreements the debit notes had been sent more frequently than every 30 seconds (probably once every 6 seconds).

**Comment by nieznanysprawiciel** [comment] 2021-04-19 09:09
@azawlocki  As for subscription `golem.srv.comp.expiration` is Agreement expiration not Demand. Demand has 60min expiration, that is set by market. As discussed with @filipgolem probably market should allow to set Demand/Offer expiration.

**Comment by azawlocki** [comment] 2021-04-19 15:18
@mbenke I'm investigating why activities are not started for some agreements, or are started with delay long enough that the provider terminates the agreement due to inactivity after 90s. Could you please add `debug_activity_api=True` and `debug_market_api=True` to the call to `enable_default_logger()` in future runs of your `yapapi` requestor?

**Comment by mbenke** [comment] 2021-04-19 19:11
@azawlocki I can do that, but these logs are going to be 100s of megs. How much data do you need?

**Comment by azawlocki** [comment] 2021-04-19 20:22
@mbenke a one hour-long computation should be enough, this shouldn't weight more than 100MB uncompressed

**Comment by mbenke** [comment] 2021-04-20 15:13
@azawlocki here's the log. Luckily it's not so big.
[yapapi210420.log.gz](https://github.com/golemfactory/yagna-triage/files/6344602/yapapi210420.log.gz)

**Comment by azawlocki** [comment] 2021-04-21 14:36
> @azawlocki here's the log. Luckily it's not so big.
> [yapapi210420.log.gz](https://github.com/golemfactory/yagna-triage/files/6344602/yapapi210420.log.gz)

@mbenke Thanks! 

Unfortunately, there's not much to analyze here. Many market and payment API calls return with errors, but none of the problems described in the current issue seems to be present in the logs. In particular:
- No agreements are terminated due to inactivity. 60 agreements are created and confirmed, for all of them activities are started, only one activity failed with a TimeoutError (but managed to compute 3 tasks before).
- All providers send their debit notes every two minutes or so, no agreements are terminated due to failure to accept debit notes.

**Closed as completed** 2021-04-28 08:48 UTC
Labels: bug, severity: major, impact: high, beta.2

**Comment by mateuszsrebrny** [comment] 2021-04-28 10:23
@mbenke we have closed this in the standup as there seems there is little more we can do, and the logs doesn't show the problems...

but now I am having second thoughts - can you please confirm the problem is fixed?

**Comment by mbenke** [comment] 2021-04-29 08:11
@mateuszsrebrny I do not know if this is fixed, but haven't seen this particular error  for a while. I will reopen or file a new issue if needed.
