### ISSUE TITLE
hyperlink does not work in handbook

### ISSUE THREAD

**Issue by ederenn** [golemfactory/yagna-triage#212] opened 2022-03-31 12:04 UTC
Name: Wojtek

[https://github.com/golemfactory/yagna-docs/blob/develop/payments/using-golem-on-mainnet/layer-2-payments.md](https://github.com/golemfactory/yagna-docs/blob/develop/payments/using-golem-on-mainnet/layer-2-payments.md) → hyperlink does not work in handbook [https://golem-network.gitbook.io/golem-sdk-develop/payments/using-golem-on-mainnet](https://golem-network.gitbook.io/golem-sdk-develop/payments/using-golem-on-mainnet)

**Comment by tworec** [comment] 2022-04-01 11:22
duplicate of https://github.com/golemfactory/yagna-docs/issues/107

**Closed as completed by tworec** 2022-04-01 11:22 UTC
