### ISSUE TITLE
Worker finished with error: Error: Request failed with status code 400

### ISSUE THREAD

**Issue by maaktweluit** [golemfactory/yagna-triage#54] opened 2021-02-03 12:52 UTC
ederenn - Win 10, js - Worker finished with error: Error: Request failed with status code 400

 ```
    2021-02-03 12:51:12 [yajsapi] info: Task sent to provider 'friendly-error', task data: 50
    ┌─────────┬──────────────┬──────────────────┬────────────────┬────────────────────┐
    │ (index) │  Agreement   │  Provider Name   │ Tasks Computed │        Cost        │
    ├─────────┼──────────────┼──────────────────┼────────────────┼────────────────────┤
    │    0    │ '0d6185f919' │ 'friendly-error' │       0        │ '0 (no invoices?)' │
    └─────────┴──────────────┴──────────────────┴────────────────┴────────────────────┘
    2021-02-03 12:51:13 [yajsapi] error: Failed to create activity for agreement a4cc36e8e4ceec89098db47dc198ebd452c687df02a3f651421860daba63d051: Error: Request failed with status code 400
    2021-02-03 12:51:13 [yajsapi] error: Worker finished with error: Error: Request failed with status code 400
 ```

**Comment by maaktweluit** [comment] 2021-02-03 12:57
no deamon logs here, but seems to appear quite often

**Comment by ederenn** [comment] 2021-02-03 13:23
[yagna_rCURRENT.log](https://github.com/golemfactory/yagna-triage/files/5918673/yagna_rCURRENT.log)
yagna deamon logs, difrent timestamps due to deamon restart, error is also appearing on second run. More examples in logs attatched above.

```2021-02-03 14:16:30 [yajsapi] error: Failed to create activity for agreement 9bfaa8500369fcb9181859975d4a58622e8e6572b9965cbfed53511e4f117711: Error: Request failed with status code 400
2021-02-03 14:16:30 [yajsapi] error: Worker finished with error: Error: Request failed with status code 400
2021-02-03 14:16:30 [yajsapi] debug: terminateAgreement(9bfaa8500369fcb9181859975d4a58622e8e6572b9965cbfed53511e4f117711) returned successfully
```

**Comment by tworec** [comment] 2021-02-04 10:53
this is a duplicate of golemfactory/yagna#921

**Closed as completed by tworec** 2021-02-04 10:53 UTC
Labels: market
