### ISSUE TITLE
Service waiting for provider though "Worker for provider 'combative-cent' failed" (timeout)

### ISSUE THREAD

**Issue by ederenn** [golemfactory/yagna-triage#130] opened 2021-06-17 11:51 UTC
Name: mf
yagna version: v0.7.0
OS+lang+version (if applicable): Ubuntu 21.04 + yapapi 787ad781b676d19ca6f9a4ad903ca04980cfd88d 

```
[2021-06-17T12:44:41.671+0200 INFO yapapi.summary] Received proposals from 14 providers so far
[2021-06-17T12:44:42.055+0200 WARNING yapapi.summary] Worker for provider 'combative-cent' failed; reason: (408)
Reason: Request Timeout
HTTP response headers: <CIMultiDictProxy('Content-Length': '21', 'Content-Type': 'application/json', 'Date': 'Thu, 17 Jun 2021 10:44:40 GMT')>
HTTP response body: {"message":"Timeout"}
...
[2021-06-17T12:44:42.796+0200 INFO yapapi.summary] Received proposals from 19 providers so far
instances: [('combative-cent', 'starting')]
...
[2021-06-17T12:48:29.254+0200 INFO yapapi.summary] Executor has shut down
Traceback (most recent call last):
  File "/home/mfra/Projects/yapapi/examples/simple-service-poc/simple_service.py", line 186, in <module>
    loop.run_until_complete(task)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/mfra/Projects/yapapi/examples/simple-service-poc/simple_service.py", line 136, in main
    raise Exception(f"Failed to start instances before {STARTING_TIMEOUT} elapsed :( ...")
Exception: Failed to start instances before 0:04:00 elapsed :( ...
```

```
[2021-06-17T12:53:12.291+0200 WARNING yapapi.summary] Worker for provider 'Duren-Nagyr' failed; reason: (500)
Reason: Internal Server Error
HTTP response headers: <CIMultiDictProxy('Content-Length': '271', 'Content-Type': 'application/json', 'Date': 'Thu, 17 Jun 2021 10:53:12 GMT')>
HTTP response body: {"message":"GSB error: Remote service at `/net/0x093236be98b05b3b3a7078a211326f29b6dee1e4/exeunit/49aedcbddae44235a35ed7dc50544697/Exec` error: Called service `/net/0x093236be98b05b3b3a7078a211326f29b6dee1e4/exeunit/49aedcbddae44235a35ed7dc50544697/Exec` is unavailable"}
...
[2021-06-17T12:53:16.771+0200 INFO yapapi.summary] Received proposals from 32 providers so far
instances: [('Duren-Nagyr', 'starting')]
```
[simple-service-yapapi-2021-06-17_12.44.25.zip](https://github.com/golemfactory/yagna-triage/files/6669908/simple-service-yapapi-2021-06-17_12.44.25.zip)

**Comment by mateuszsrebrny** [comment] 2021-06-17 12:09
@golemfactory/ya-sdk could you please have a look if this is very bad?
And if this is yapapi side?

**Comment by azawlocki** [comment] 2021-06-17 13:05
What's in the log:

One service instance has been requested, an agreement has been confirmed, an activity started successfully for this agreement.

Then a timeout error (`ApiException 408`) occurred when the requestor tried to send the first script (the one with `deploy` and `start`) to the provider:
```
[2021-06-17T12:44:34.871+0200 DEBUG ya_activity.rest] request: {'method': 'POST', 'url': 'http://127.0.0.1:7465/activity-api/v1/activity/d053b76840434dfaa7e5933e6029c2c0/exec', 'timeout': 300, 'headers': {'Accept': 'application/json', 'Content-Type': 'application/json', 'authorization': 'Bearer b8c5d1279e274343a3b0baafbe5ce67b', 'User-Agent': 'OpenAPI-Generator//python'}, 'data': '{"text": "[{\\"deploy\\": {}}, {\\"start\\": {\\"args\\": []}}, {\\"run\\": {\\"entry_point\\": \\"/golem/run/simulate_observations_ctl.py\\", \\"args\\": [\\"--start\\"], \\"capture\\": {\\"stdout\\": {\\"stream\\": {}}, \\"stderr\\": {\\"stream\\": {}}}}}]"}'}
...
[2021-06-17T12:44:40.875+0200 DEBUG ya_activity.rest] response body: b'{"message":"Timeout"}'
```
`yapapi` does not pass errors like this to the user code but just kills the activity and the instance.

**Comment by azawlocki** [comment] 2021-06-17 13:11
Related to: https://github.com/golemfactory/yapapi/issues/476

**Comment by mateuszsrebrny** [comment] 2021-07-05 09:50
seems to be fixed by now

**Closed as completed by mateuszsrebrny** 2021-07-05 09:50 UTC
Labels: sdk, severity: major, impact: low

**Comment by azawlocki** [comment] 2021-07-05 09:54
Should be fixed by https://github.com/golemfactory/yapapi/pull/498
