### ISSUE TITLE
Yagna requestor run out of file descriptors

### ISSUE THREAD

**Issue by etam** [golemfactory/yagna-triage#232] opened 2022-11-02 10:27 UTC
yagna version: 0.11.0 (5c693052 2022-09-14 build #236)

At some point yagna started eating a lot of memory and run out of file descriptors.

Memory usage:
![Screenshot_20221102_112555](https://user-images.githubusercontent.com/220752/199466248-b9fecad4-8c10-4695-b6ce-9f5fbffd71f1.png)

File descriptors (blue line):
![Screenshot_20221102_112617](https://user-images.githubusercontent.com/220752/199466310-e8aa85d3-c790-49e0-873b-de8380dc043f.png)

datadir: https://drive.google.com/file/d/1t4oHpqVi3HsFKsK6b9yMq9gz055Ro4OF/view?usp=sharing

**Comment by kamirr** [comment] 2022-11-03 15:24
Descriptor leaks are an ongoing issue, see e.g. https://github.com/golemfactory/yagna/issues/2253.

Not much can be inferred from attached logs, after a discussion with Witek we opted to add appropriate measurements to yagna to help with tackling the issue when it comes up again in the future: https://github.com/golemfactory/yagna/issues/2276

Moving to observed for the time being.

**Comment by etam** [comment] 2022-11-28 10:26
Still happening...
![Screenshot_20221128_092725](https://user-images.githubusercontent.com/220752/204254674-21e95361-24f9-4d3a-aa51-bb11a85cabf9.png)

**Comment by evik42** [comment] 2022-12-02 12:09
I could not reproduce it after a yagna restart. Tried different setups. We have metrics in place to monitor the different types of file descriptors and after the release these will be available in the requestors to help in investigation.

**Comment by golmek** [comment] 2023-06-01 12:26
Not able to be replicated.  ticket being closed.

**Closed as not planned** 2023-06-01 12:26 UTC
