### ISSUE TITLE
Yacat sends task to failed provider

### ISSUE THREAD

**Issue by maaktweluit** [golemfactory/yagna-triage#146] opened 2021-08-12 12:29 UTC
Name: Yacat sends task to failed provider
yagna version: 0.7.3
OS+lang+version (if applicable): python 0.6.3a1 
Title: 
!!! attach `blender-yapapi.log`, zipped data-dir !!!

```
    [2021-08-12T12:48:26.287+0200 INFO yapapi.summary] Agreement proposed to provider 'Ortobuntu'
    [2021-08-12T12:48:27.151+0200 INFO yapapi.summary] Received proposals from 18 providers so far
    [2021-08-12T12:48:27.254+0200 INFO yapapi.summary] Agreement confirmed by provider 'Ortobuntu'
    [2021-08-12T12:48:28.208+0200 INFO yapapi.summary] Task started on provider 'Ortobuntu', task data: compute_keyspace
    [2021-08-12T12:51:35.063+0200 WARNING yapapi.summary] Worker for provider 'Ortobuntu' failed; reason: Failed to compute attack keyspace: Command '{'deploy': {}}' failed on provider; message: 'Local service error: Transfer error: Downloaded VM image is corrupted: calculated hash aaf6fc8d4a5e408bd48bfc3fa2db03f032a2351f401f245cfda32fce differs from the expected one 055911c811e56da4d75ffc928361a78ed13077933ffa8320fb1ec2db'
    [2021-08-12T12:51:37.918+0200 INFO yapapi.summary] Terminated agreement with Ortobuntu
    [2021-08-12T12:51:37.924+0200 INFO yapapi.summary] Agreement proposed to provider 'erar02'
    [2021-08-12T12:51:38.930+0200 INFO yapapi.summary] Accepted invoice from 'Ortobuntu', amount: 0.001266923603272222
    [2021-08-12T12:51:40.280+0200 INFO yapapi.summary] Agreement proposed to provider 'many-mine'
    [2021-08-12T12:51:42.385+0200 INFO yapapi.summary] Agreement proposed to provider 'Ortobuntu'
    [2021-08-12T12:51:43.654+0200 INFO yapapi.summary] Agreement confirmed by provider 'Ortobuntu'
    [2021-08-12T12:51:44.608+0200 INFO yapapi.summary] Task started on provider 'Ortobuntu', task data: compute_keyspace
```

**Comment by mateuszsrebrny** [comment] 2021-09-27 12:18
@shadeofblue this is the market strategy that didn't make into beta.3, right?
Should I mark it beta.4 then? (ie next release whatever the official name will be?)

**Comment by mateuszsrebrny** [comment] 2021-10-21 11:38
functions as intended (sadly) closing

**Closed as completed by mateuszsrebrny** 2021-10-21 11:38 UTC
