### ISSUE TITLE
yajsapi - some logs printed after return to shell after ctrl+c

### ISSUE THREAD

**Issue by ederenn** [golemfactory/yagna-triage#9] opened 2020-12-15 12:50 UTC
Etam - linux+js - some logs printed after return to shell after ctrl+c

```jsx
2020-11-30 11:53:51 [yajsapi] info: Received proposals from 8 providers so far
^C
etam@0fd751d2d5d3:~/yajsapi/examples> 2020-11-30 11:53:52 [yajsapi] error: Unexpected token u in JSON at position 0
2020-11-30 11:53:53 [yajsapi] error: fail= undefined
2020-11-30 11:54:05 [yajsapi] debug: GFTP server closed, code=SIGINT
```

**Comment by shadeofblue** [comment] 2021-02-08 12:11
duplicate of https://github.com/golemfactory/yagna-triage/issues/50

**Closed as completed by shadeofblue** 2021-02-08 12:11 UTC
Labels: duplicate, sdk, beta.1
